# Generated by Django 4.2.3 on 2023-07-20 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redactor",
            options={"verbose_name": "redactor", "verbose_name_plural": "redactors"},
        ),
        migrations.CreateModel(
            name="Newspaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("published_date", models.DateField()),
                (
                    "redactors",
                    models.ManyToManyField(
                        related_name="newspapers", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.topic"
                    ),
                ),
            ],
        ),
    ]
