# Generated by Django 4.2.3 on 2023-07-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_redactor_options_newspaper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="year_of_experience",
            field=models.IntegerField(null=True),
        ),
    ]
