# Generated by Django 4.2.3 on 2023-07-20 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_redactor_year_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["id"]},
        ),
    ]
